# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('state', models.BooleanField(verbose_name='操作类型')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='彩金类型')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='姓名')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='彩金')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ')),
                ('tel', models.CharField(max_length=15, verbose_name='电话号码')),
                ('email', models.CharField(max_length=25, verbose_name='邮箱')),
                ('state', models.BooleanField(default=False, verbose_name='状态')),
                ('tagname', models.CharField(max_length=50, verbose_name='数据标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='派送时间')),
                ('operator', models.CharField(blank=True, max_length=35, null=True, verbose_name='操作人')),
                ('lotteryclass', models.CharField(default='', max_length=35, verbose_name='彩金类型')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataname', models.CharField(max_length=50, unique=True, verbose_name='数据包名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('filename', models.CharField(max_length=50, unique=True, verbose_name='文件名称')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='导入数量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('bywho', models.CharField(max_length=35, verbose_name='上传人')),
                ('del_person', models.CharField(default='', max_length=35, verbose_name='删除人')),
            ],
        ),
    ]
